#include<iostream>
using namespace std;
int main()
{
    
	cout<<"* Helplinen                                                                      "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"		S.No				CITY			CONTACT DETAILS                         "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"		Police Control Room		Anywhere in India	100                             "<<endl;
    cout<<"		Fire Control Room		New Delhi		101                                 "<<endl;
    cout<<"		Ambulance Helpline		New Delhi		102                                 "<<endl;
    cout<<"		Centralised Accident &                                                      "<<endl;
    cout<<"		Trauma Services (CATS)		New Delhi		1099                            "<<endl;
    cout<<"		Ambulance Helpline 		New Delhi		1092                                "<<endl;
    cout<<"		Women's Helpline		New Delhi		1091                                "<<endl;
    cout<<"		Women's Helpline		Anywhere in India	181                             "<<endl;
    cout<<"		Senior Citizen Helpline		New Delhi		1091 , 1291                     "<<endl;
    cout<<"		Anti-Obscene Calls Cell		New Delhi		1091	                        "<<endl;
    cout<<"		Anti Stalking Cell		New Delhi		1091                                "<<endl;
    cout<<"		AIDS Helpline			Anywhere in India	1097                            "<<endl;
    cout<<"		Medical Helpline, State		Andhra Pradesh, Gujarat,                        "<<endl;
    cout<<"						Uttarakhand, Goa, Tamil                                     "<<endl;
    cout<<"						Nadu, Rajasthan,                                            "<<endl;
    cout<<"						Karnataka, Assam,                                           "<<endl;
    cout<<"						Meghalaya, Madhya Pradesh                                   "<<endl;
    cout<<"						and Uttar Pradesh	108                                     "<<endl;
    cout<<"		Anti Poison			New Delhi		1066                                    "<<endl;
    cout<<"		Eye Donation			New Delhi		1919                                "<<endl;
    cout<<"		Fire Control Room		New Delhi		101                                 "<<endl;
    cout<<"		Indian Red Cross Society	New Delhi		011- 23711551                   "<<endl;
    cout<<"		Directory Enquiry		New Delhi		197                                 "<<endl;
    cout<<"		CGHS Helpline, Directorate                                                  "<<endl;
    cout<<"		General of Health Services	New Delhi		155224                          "<<endl;
    cout<<"		Institute of Liver and Biliary                                              "<<endl;
    cout<<"		Sciences			New Delhi		155353                                  "<<endl;
    cout<<"		Disaster Management of Govt.                                                "<<endl;
    cout<<"		of NCT of Delhi			New Delhi		1077                                "<<endl;
    cout<<"		Dy.Commissioner of Police                                                   "<<endl;
    cout<<"		(Missing Children and Women)	New Delhi		1094                        "<<endl;
    cout<<"		Traffic Police Helpline		New Delhi		1095                            "<<endl;
    cout<<"		Delhi Police Helpline		New Delhi		1090                            "<<endl;
    cout<<"		Helpline of NDMC Control Room	New Delhi		1267                        "<<endl;
    cout<<"		Ambulance Service		New Delhi		1066                                "<<endl;
    cout<<"		Helpline for Women		New Delhi		1092                                "<<endl;
    cout<<"		ORBO C.N.Centre, AIIMS                                                      "<<endl;
    cout<<"		(for donation of organs)	New Delhi		1060                            "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;		
    cout<<"	                        	* BLOOD BANKS IN DELHI/NCR *                        "<<endl;
    cout<<"                                                                                 "<<endl;		
    cout<<"		EMERGENCY HELPLINES.		CITY			CONTACT DETAILS                 "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;		
    cout<<"		AIIMS				New Delhi		011- 26593726, 26594438                 "<<endl;
    cout<<"		Rotary Noida Blood Bank		New Delhi		011- 66364887                   "<<endl;
    cout<<"		White Cross Blood Bank		New Delhi		011- 26831063, 26844140         "<<endl;
    cout<<"		Batra Hospital and Medical                                                  "<<endl;
    cout<<"		Research Centre			New Delhi		011- 29958747, 29957487, 29956509   "<<endl;
    cout<<"		Majeedia Hospital		New Delhi		011- 64788237, 64788249             "<<endl;
    cout<<"		Apollo Blood Bank		New Delhi		011- 26825707, 26925858, 26925801   "<<endl;
    cout<<"		Lions Blood Bank		New Delhi		011- 42258080, 42258494             "<<endl;
    cout<<"		Dharmashila Cancer Foundation                                               "<<endl;
    cout<<"		& Research Centre		New Delhi		011- 43066424-25, 22617771-75       "<<endl;
    cout<<"		Sir Ganga Ram Hospital		New Delhi		011 - 25750000, 25751111        "<<endl;
    cout<<"		Indian Red Cross Society	New Delhi		011 - 23711551                  "<<endl;
    cout<<"		Batra Hospital & Medical                                                    "<<endl;
    cout<<"		Research Centre			New Delhi		011-26056148, 26056153, 26057154    "<<endl;
    cout<<"		Jai Prakash Narayan Apex                                                    "<<endl;
    cout<<"		Trauma Centre			New Delhi		011- 2673 1166, 2673 1179           "<<endl;
    cout<<"		Max Balaji Hospital		New Delhi		011- 66242515, Extension- 2031      "<<endl;
    cout<<"		Fortis Flt. Lt. Rajan Dhall                                                 "<<endl;
    cout<<"		Hospital			New Delhi		011- 42776222, Extension- 5850          "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"                                                                                 "<<endl;		
    cout<<"		* 24 HOUR AMBULANCE IN DELHI                                                "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		EMERGENCY HELPLINES.		CITY			CONTACT DETAILS                 "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		All India Institute of                                                      "<<endl;
    cout<<"		Medical Sciences (AIIMS)	New Delhi		011- 26588776                   "<<endl;
    cout<<"		Centralized Accident Trauma                                                 "<<endl;
    cout<<"		Service (CATS)			New Delhi		102, 1099                           "<<endl;
    cout<<"		Escort Hospital			New Delhi		011- 26825000                       "<<endl;
    cout<<"		Moolchand Hospital		New Delhi		011- 42000000                       "<<endl;
    cout<<"		Batra Hospital			New Delhi		011- 26083747                       "<<endl;
    cout<<"		Rajiv Gandhi Cancer Institute	New Delhi		011- 27051011 to 29         "<<endl;
    cout<<"		National Heart Institute	New Delhi		011- 26441293                   "<<endl;
    cout<<"		Sir Ganga Ram Hospital		New Delhi		011- 25750000, 25757575         "<<endl;
    cout<<"		Vidyasagar Institute of Mental                                              "<<endl;
    cout<<"		Health and NeuroSciences                                                    "<<endl;
    cout<<"		(VIMHANS)			New Delhi		011- 26924302                           "<<endl;
    cout<<"		All India Institute of Medical                                              "<<endl;
    cout<<"		Sciences (AIIMS)		New Delhi		011- 26588776                       "<<endl;
    cout<<"		AIDS Diagnostic Centre		New Delhi		011- 64360750                   "<<endl;
    cout<<"		Delhi Psychiatry Centre		New Delhi		011- 2214727                    "<<endl;
    cout<<"		MP Heart Centre			New Delhi		011- 6413436                        "<<endl;
    cout<<"		National Heart Institute	New Delhi		011- 6414156                    "<<endl;
    cout<<"		Anand Hospital			New Delhi		011- 2224126                        "<<endl;
    cout<<"		Holy Angles Hospital		New Delhi		011- 6143411                    "<<endl;
    cout<<"		GM Modi Hospital		New Delhi		011- 6852112                        "<<endl;
    cout<<"		PS Funeral & Ambulance Services                                             "<<endl;
    cout<<"		Private Limited			New Delhi		09350016581, 08373903017            "<<endl;
    cout<<"		Max Emergency Ambulance		New Delhi		011- 40554055                   "<<endl;
    cout<<"		Goodmans Rescue Ambulance                                                   "<<endl;
    cout<<"		Service				New Delhi		011- 29231665, 46566890                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		* MISCELLANEOUS                                                             "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		NON-EMERGENCY HELPLINES		CITY			CONTACT DETAILS                 "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"		Insurance Regulatory and Development                                        "<<endl;
    cout<<"		 Authority (IRDA)	Anywhere in India	155255/ 1800 4254732                "<<endl;
    cout<<"		Reproductive Health, Family                                                 "<<endl; 
    cout<<"		Planning and Infant Health	New Delhi		1800-11-6555                    "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"                                                                                 "<<endl;	
}
