#include<iostream>
using namespace std;
int main()
{
    
	cout<<"* Helplinen                                                                      "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"		S.No				CITY			CONTACT DETAILS                         "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"		Police Control Room		Anywhere in India	100                             "<<endl;
    cout<<"		Fire Control Room		Mumbai 		        101                         "<<endl;
    cout<<"		Ambulance Helpline		Mumbai 			102                                 "<<endl;
    cout<<"		Centralised Accident &                                                      "<<endl;
    cout<<"		Trauma Services (CATS)		Mumbai		        1099                            "<<endl;
    cout<<"		Ambulance Helpline 		Mumbai		        1092                                "<<endl;
    cout<<"		Women's Helpline		Mumbai		        1091                                "<<endl;
    cout<<"		Women's Helpline		Anywhere in India	181                             "<<endl;
    cout<<"		Senior Citizen Helpline		Mumbai		        1091 , 1291                     "<<endl;
    cout<<"		Anti-Obscene Calls Cell		Mumbai		        1091	                        "<<endl;
    cout<<"		Anti Stalking Cell		Mumbai		        1091                                "<<endl;
    cout<<"		AIDS Helpline			Anywhere in India	1097                            "<<endl;
    cout<<"		Medical Helpline, State		Maharashtra                        "<<endl;
    cout<<"						                                     "<<endl;
    cout<<"						                                            "<<endl;
    cout<<"						                                           "<<endl;
    cout<<"						                                   "<<endl;
    cout<<"										                                     "<<endl;
    cout<<"		Anti Poison			Mumbai		        1066                                    "<<endl;
    cout<<"		Eye Donation			Mumbai			1919                                "<<endl;
    cout<<"		Fire Control Room		Mumbai 			101                                 "<<endl;
    cout<<"		Indian Red Cross Society	Mumbai			011- 23711551                   "<<endl;
    cout<<"		Directory Enquiry		Mumbai			197                                 "<<endl;
    cout<<"		CGHS Helpline, Directorate                                                  "<<endl;
    cout<<"		General of Health Services	Mumbai			155224                          "<<endl;
    cout<<"		Institute of Liver and Biliary                                              "<<endl;
    cout<<"		Sciences			Mumbai			155353                                  "<<endl;
    cout<<"		Disaster Management of Govt.                                                "<<endl;
    cout<<"		of NCT of Delhi			Mumbai			1077                                "<<endl;
    cout<<"		Dy.Commissioner of Police                                                   "<<endl;
    cout<<"		(Missing Children and Women)	Mumbai			1094                        "<<endl;
    cout<<"		Traffic Police Helpline		Mumbai			1095                            "<<endl;
    cout<<"		Delhi Police Helpline		Mumbai			1090                            "<<endl;
    cout<<"		Helpline of NDMC Control Room	Mumbai			1267                        "<<endl;
    cout<<"		Ambulance Service		Mumbai			1066                                "<<endl;
    cout<<"		Helpline for Women		Mumbai 			1092                                "<<endl;
    cout<<"		ORBO C.N.Centre, AIIMS                                                      "<<endl;
    cout<<"		(for donation of organs)	Mumbai 			1060                            "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;		
    cout<<"	                        	* BLOOD BANKS IN MUMBAI *                        "<<endl;
    cout<<"                                                                                 "<<endl;		
    cout<<"		EMERGENCY HELPLINES.		CITY			CONTACT DETAILS                 "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;		
    cout<<"		AIIMS				Mumbai 			022- 26593726, 26594438                 "<<endl;
    cout<<"		Bombay Hospital			Mumbai			022- 66364887                   "<<endl;
    cout<<"		White Cross Blood Bank		Mumbai  		022- 26831063, 26844140        "<<endl;
    cout<<"		Batra Hospital and Medical                                                  "<<endl;
    cout<<"		Research Centre			Mumbai			022- 29958747, 29957487, 29956509   "<<endl;
    cout<<"		Bhagvati Hospital		Mumbai			022- 64788237, 64788249             "<<endl;
    cout<<"		Apollo Blood Bank		Mumbai 			022- 26825707, 26925858, 26925801   "<<endl;
    cout<<"		Lions Blood Bank		Mumbai 			022- 42258080, 42258494             "<<endl;
    cout<<"		Dharmashila Cancer Foundation                                               "<<endl;
    cout<<"		& Research Centre		Mumbai			022- 43066424-25, 22617771-75       "<<endl;
    cout<<"		Sir JJ Hospital			Mumbai			022 - 25750000, 25751111         "<<endl;
    cout<<"		Indian Red Cross Society	Mumbai			022 - 23711551                  "<<endl;
    cout<<"		Batra Hospital & Medical                                                    "<<endl;
    cout<<"		Research Centre			Mumbai			022-26056148, 26056153, 26057154    "<<endl;
    cout<<"		Jai Prakash Narayan Apex                                                    "<<endl;
    cout<<"		Trauma Centre			Mumbai		 	022- 2673 1166, 2673 1179           "<<endl;
    cout<<"		Max Balaji Hospital		Mumbai 			022- 66242515, Extension- 2031      "<<endl;
    cout<<"		Fortis Flt. Lt. Rajan Dhall                                                 "<<endl;
    cout<<"		Hospital			Mumbai 			022- 42776222, Extension- 5850          "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"                                                                                 "<<endl;		
    cout<<"		* 24 HOUR AMBULANCE IN MUMBAI                                                "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		EMERGENCY HELPLINES.		CITY			CONTACT DETAILS                 "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		All India Institute of                                                      "<<endl;
    cout<<"		Medical Sciences (AIIMS)	Mumbai			022- 26588776                   "<<endl;
    cout<<"		Centralized Accident Trauma                                                 "<<endl;
    cout<<"		Service (CATS)			Mumbai 			102, 1099                           "<<endl;
    cout<<"		Escort Hospital			Mumbai 			022- 26825000                       "<<endl;
    cout<<"		Moolchand Hospital		Mumbai			022- 42000000                       "<<endl;
    cout<<"		Batra Hospital			Mumbai 			022- 26083747                       "<<endl;
    cout<<"		Rajiv Gandhi Cancer Institute	Mumbai 			022- 27051011 to 29         "<<endl;
    cout<<"		National Heart Institute	Mumbai 			022- 26441293                   "<<endl;
    cout<<"		Sir Ganga Ram Hospital		Mumbai			022- 25750000, 25757575         "<<endl;
    cout<<"		Vidyasagar Institute of Mental                                              "<<endl;
    cout<<"		Health and NeuroSciences                                                    "<<endl;
    cout<<"		(VIMHANS)			Mumbai			022- 26924302                           "<<endl;
    cout<<"		All India Institute of Medical                                              "<<endl;
    cout<<"		Sciences (AIIMS)		Mumbai 			022- 26588776                       "<<endl;
    cout<<"		AIDS Diagnostic Centre		Mumbai 			022- 64360750                   "<<endl;
    cout<<"		Delhi Psychiatry Centre		Mumbai			022- 2214727                    "<<endl;
    cout<<"		MP Heart Centre			Mumbai			022- 6413436                        "<<endl;
    cout<<"		National Heart Institute	Mumbai 			022- 6414156                    "<<endl;
    cout<<"		Anand Hospital			Mumbai			022- 2224126                        "<<endl;
    cout<<"		Holy Angles Hospital		Mumbai			022- 6143411                    "<<endl;
    cout<<"		GM Modi Hospital		Mumbai			022- 6852112                        "<<endl;
    cout<<"		PS Funeral & Ambulance Services                                             "<<endl;
    cout<<"		Private Limited			Mumbai 			09350016581, 08373903017            "<<endl;
    cout<<"		Max Emergency Ambulance		Mumbai 			022 - 40554055                   "<<endl;
    cout<<"		Goodmans Rescue Ambulance                                                   "<<endl;
    cout<<"		Service				Mumbai			022 - 29231665, 46566890                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		* MISCELLANEOUS                                                             "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"		NON-EMERGENCY HELPLINES		CITY			CONTACT DETAILS                 "<<endl;
    cout<<"		____________________________________________________________________________"<<endl;
    cout<<"                                                                                 "<<endl;
    cout<<"		Insurance Regulatory and Development                                        "<<endl;
    cout<<"		 Authority (IRDA)		Anywhere in India	155255/ 1800 4254732                "<<endl;
    cout<<"		Reproductive Health, Family                                                 "<<endl; 
    cout<<"		Planning and Infant Health	Mumbai			1800-11-6555                    "<<endl;
    cout<<"                                                                                 "<<endl;	
    cout<<"                                                                                 "<<endl;	
}
